### ISSUE TITLE
Beware of Node Engine changes in a patch version

### ISSUE THREAD

**Issue by DavidPineauScality** [Level/iterator-stream#36] opened 2018-06-28 15:27 UTC
Hello,

I'm opening this issue with the aim of informing/notifying you of an issue related to a recent change in the package.json file of this project.

Long story short, Defining the `engine` requirement in the package.json file for the `2.0.0` -> `2.0.1` version bump led to broken installs of projects which depend on yours when using an older Node LTS version than what was specified in the file.
As other projects tend to depend loosely on the minor versions of their dependencies in the Node.js community (ie: `~2.0.0`), such change may subtly break the installation when the environment is slightly different from your expectations.

Note that I completely understand the usefulness of such specification, notably when one language feature used requires a more recent Node.js engine version; but I think it should be kept for major versions only, according to Semantic Versionning.

See the complete explanation here: https://github.com/Level/levelup/issues/593

Cheers !

**Comment by vweevers** [comment] 2018-06-28 15:50
We always bump major when dropping node versions, but we did make a mistake here. Postmortem:

- `level-iterator-stream` dropped node 4 in `2.0.0` (but this was not added to `engines` until 2.0.1)
- `levelup` dropped node 4 in `2.0.0-rc1`
- `levelup` upgraded to `level-iterator-stream@~2.0.0` in `2.0.0-rc1`
- After some discussion, `levelup` restored node 4 in `2.0.1`
- `levelup` dropped node 4 again in `3.0.0`

So, the mistake is that though we restored node 4 in `levelup`, we did not restore it in `level-iterator-stream`. Our apologies @DavidPineauScality.

@ralphtheninja what can we do about this? Did we make any changes to `level-iterator-stream` that are incompatible with node 4? If not, the problem is only an npm warning.

@DavidPineauScality does yarn warn like npm, or does it actually refuse to install an incompatible version?

**Comment by DavidPineauScality** [comment] 2018-06-28 16:03
No worries :)

I've been fiddling with this, NPM seems to be much more lenient relatively to this specific issue (and lets the dependencies install despite the engine incompatibility?)

Yarn, though, needs the --ignore-engines options to be able to go past this (at least in my meager experience)

**Comment by DavidPineauScality** [comment] 2018-06-28 16:03
Note that in the orignial issue, what I pasted was a hard failure from Yarn (error, not warning)

**Comment by vweevers** [comment] 2018-06-28 16:14
Yeah, it's only advisory in `npm` (as it should be IMO). To please `yarn`, we could:

- Release a patch (2.0.2) with `engines >= 4`
- Release a new major (3.0.0) with `engines >= 6`.

@ralphtheninja WDYT?

**Comment by ralphtheninja** [comment] 2018-06-28 16:17
We actually never removed node 4, it was never added. What happened was that `engines` was added and released in `2.0.1` (diff https://github.com/level/iterator-stream/compare/v2.0.0...v2.0.1).

> Release a patch (2.0.2) with engines >= 4
> Release a new major (3.0.0) with engines >= 6.

SGTM! (I had the exact same thought).

**Comment by ralphtheninja** [comment] 2018-06-28 16:18
@vweevers Wanna do the honors? If not, I could do it right now.

**Comment by vweevers** [comment] 2018-06-28 16:18
> We actually never removed node 4, it was never added. 

ab24beb91b13b5c533ca7b22431a7c683af40147

**Comment by vweevers** [comment] 2018-06-28 16:19
@ralphtheninja go ahead

**Comment by ralphtheninja** [comment] 2018-06-28 16:30
https://github.com/Level/iterator-stream/releases/tag/v2.0.2

@DavidPineauScality Thanks for reporting this!

**Closed by ralphtheninja** 2018-06-28 16:30 UTC

**Comment by DavidPineauScality** [comment] 2018-06-28 16:32
Thank you for being that reactive ! ;)
